# Generated by Django 4.2.3 on 2023-09-04 11:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(max_length=1000)),
                ('founded_at', models.DateField(auto_now_add=True)),
                ('population', models.CharField(choices=[('1-10', '1-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('بیشتر از 500', 'بیشتر از 500')], max_length=15)),
                ('Owner_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('Phone', models.CharField(max_length=100)),
                ('Adress', models.TextField(max_length=1000)),
                ('Working_days_from', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], max_length=15)),
                ('Working_days_to', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], default='16;00', max_length=15)),
                ('working_hours_from', models.TimeField()),
                ('working_hours_to', models.TimeField()),
                ('active_plan', models.CharField(blank=True, choices=[('ینبادی', 'ینبادی'), ('پیشرفته', 'پیشرفته')], max_length=15, null=True)),
                ('available_Job_count', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfession_title', models.CharField(max_length=100, null=True)),
                ('cooperation_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت')], max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(max_length=1000, null=True)),
                ('gender', models.CharField(choices=[('خانوم', 'خانوم'), ('آقا', 'آقا')], default='خانوم', max_length=15)),
                ('cv', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت')], max_length=15)),
                ('isremote', models.BooleanField(default=False)),
                ('experience', models.CharField(choices=[('بدون محدودیت', 'بدون محدودیت'), ('کمتر از ۲ سال', 'کمتر از ۲ سال'), ('۲ تا ۵ سال', '۲ تا ۵ سال'), ('بیشتر از ۵ سال', 'بیشتر از ۵ سال')], default='بدون محدودیت', max_length=15)),
                ('level', models.CharField(choices=[('intern(کاراموز)', 'intern(کاراموز)'), ('Junior(جوان)', 'Junior(جوان)'), ('Senior(ارشد)', 'Senior(ارشد)'), ('Lead(راهبر)', 'Lead(راهبر)')], default='Junior(جوان)', max_length=15)),
                ('salary_type', models.CharField(choices=[('توافقی', 'توافقی'), ('مشخص', 'مشخص')], default='توافقی', max_length=15)),
                ('salary_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('درانتظار تایید', 'درانتظار تایید'), ('تکمیل شده', 'تکمیل شده'), ('منقضی شده', 'منقضی شده')], max_length=15)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationـnumber', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('درانتظار تایید', 'درانتظار تایید'), ('حذف', 'حذف')], default='در انتظار بررسی', max_length=15)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('send_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('در انتظار بررسی', 'در انتظار بررسی'), ('بررسی شده', 'بررسی شده'), ('رد شده', 'رد شده'), ('استخدام شده', 'استخدام شده')], default='درانتظار بررسی', max_length=15)),
                ('status_change_date', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.job')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('rate', models.CharField(choices=[('100', '100'), ('90', '90'), ('80', '80'), ('70', '70'), ('60', '60'), ('50', '50'), ('40', '40'), ('30', '30'), ('20', '20'), ('10', '10')], max_length=15)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='base.skills'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='favorite_jobs',
            field=models.ManyToManyField(blank=True, null=True, to='base.job'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='base.skills'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=15)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='favorite_employee',
            field=models.ManyToManyField(blank=True, null=True, to='base.employee'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.state'),
        ),
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('employee', 'job'), name='unique_employee_job'),
        ),
    ]
