# Generated by Django 4.2.3 on 2023-07-31 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(max_length=1000)),
                ('founded_at', models.DateField(auto_now_add=True)),
                ('city', models.CharField(choices=[('اراک', 'اراک'), ('اصفهان', 'اصفهان'), ('ایلام', 'ایلام'), ('بجنورد', 'بجنورد'), ('بندرعباس', 'بندرعباس'), ('بوشهر', 'بوشهر'), ('تبریز', 'تبریز'), ('تهران', 'تهران'), ('خرم\u200cآباد', 'خرم\u200cآباد'), ('رشت', 'رشت'), ('ساری', 'ساری'), ('سمنان', 'سمنان'), ('سنندج', 'سنندج'), ('شهرکرد', 'شهرکرد'), ('شیراز', 'شیراز'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کرج', 'کرج'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('گرگان', 'گرگان'), ('مشهد', 'مشهد'), ('همدان', 'همدان'), ('یاسوج', 'یاسوج'), ('زاهدان', 'زاهدان'), ('زنجان', 'زنجان'), ('اردبیل', 'اردبیل'), ('ارومیه', 'ارومیه'), ('اهواز', 'اهواز')], default='تهران', max_length=15)),
                ('population', models.CharField(choices=[('1-10', '1-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('بیشتر از ۵۰۰', 'بیشتر از ۵۰۰')], max_length=15)),
                ('Owner_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('Phone', models.CharField(max_length=100)),
                ('Adress', models.TextField(max_length=1000)),
                ('Working_days_from', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], max_length=15)),
                ('working_hours_from', models.TimeField()),
                ('working_hours_to', models.TimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15)),
                ('isremote', models.BooleanField(default=False)),
                ('city', models.CharField(choices=[('اراک', 'اراک'), ('اصفهان', 'اصفهان'), ('ایلام', 'ایلام'), ('بجنورد', 'بجنورد'), ('بندرعباس', 'بندرعباس'), ('بوشهر', 'بوشهر'), ('تبریز', 'تبریز'), ('تهران', 'تهران'), ('خرم\u200cآباد', 'خرم\u200cآباد'), ('رشت', 'رشت'), ('ساری', 'ساری'), ('سمنان', 'سمنان'), ('سنندج', 'سنندج'), ('شهرکرد', 'شهرکرد'), ('شیراز', 'شیراز'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کرج', 'کرج'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('گرگان', 'گرگان'), ('مشهد', 'مشهد'), ('همدان', 'همدان'), ('یاسوج', 'یاسوج'), ('زاهدان', 'زاهدان'), ('زنجان', 'زنجان'), ('اردبیل', 'اردبیل'), ('ارومیه', 'ارومیه'), ('اهواز', 'اهواز')], default='تهران', max_length=15)),
                ('experience', models.CharField(choices=[('بدون محدودیت', 'بدون محدودیت'), ('کمتر از ۲ سال', 'کمتر از ۲ سال'), ('۲ تا ۵ سال', '۲ تا ۵ سال'), ('بیشتر از ۵ سال', 'بیشتر از ۵ سال')], default='بدون محدودیت', max_length=15)),
                ('level', models.CharField(choices=[('intern(کاراموز)', 'intern(کاراموز)'), ('Junior(جوان)', 'Junior(جوان)'), ('Senior(ارشد)', 'Senior(ارشد)'), ('Lead(راهبر)', 'Lead(راهبر)')], default='Junior(جوان)', max_length=15)),
                ('salary_type', models.CharField(choices=[('توافقی', 'توافقی'), ('مشخص', 'مشخص')], default='توافقی', max_length=15)),
                ('salary_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('skills_required', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.skills')),
            ],
        ),
    ]
