# Generated by Django 4.2.3 on 2023-07-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Working_days_to',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنج شنبه', 'پنج شنبه'), ('جمعه', 'جمعه')], default='16;00', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='population',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('بیشتر از 500', 'بیشتر از 500')], max_length=15),
        ),
    ]
