# Generated by Django 4.2.3 on 2023-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('درانتظار تایید', 'درانتظار تایید'), ('حذف شده', 'حذف شده')], default='در انتظار بررسی', max_length=15),
        ),
    ]
