# Generated by Django 4.2.3 on 2023-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_country_company_favorite_employee_verification_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='favorite_employee',
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('اراک', 'اراک'), ('اصفهان', 'اصفهان'), ('ایلام', 'ایلام'), ('بجنورد', 'بجنورد'), ('بندرعباس', 'بندرعباس'), ('بوشهر', 'بوشهر'), ('تبریز', 'تبریز'), ('تهران', 'تهران'), ('خرم\u200cآباد', 'خرم\u200cآباد'), ('رشت', 'رشت'), ('ساری', 'ساری'), ('سمنان', 'سمنان'), ('سنندج', 'سنندج'), ('شهرکرد', 'شهرکرد'), ('شیراز', 'شیراز'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کرج', 'کرج'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('گرگان', 'گرگان'), ('مشهد', 'مشهد'), ('همدان', 'همدان'), ('یاسوج', 'یاسوج'), ('زاهدان', 'زاهدان'), ('زنجان', 'زنجان'), ('اردبیل', 'اردبیل'), ('ارومیه', 'ارومیه'), ('اهواز', 'اهواز')], default='تهران', max_length=15),
        ),
    ]
