# Generated by Django 4.2.3 on 2023-09-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_company_about_alter_company_user'),
        ('base', '0004_portfolio_image_data_alter_company_about_and_more'),
    ]

    operations = [
    ]
