# Generated by Django 4.2.3 on 2023-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_20230906_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='manual_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
