# Generated by Django 4.2.3 on 2023-08-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Company',
            new_name='company',
        ),
    ]
