# Generated by Django 4.2.3 on 2023-08-03 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_verification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='favorite_employee',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=[], null=True), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
