# Generated by Django 4.2.3 on 2023-09-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_gallery_company_alter_job_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_data',
        ),
    ]
