# Generated by Django 4.2.3 on 2023-08-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_company_gallery_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_plan',
            field=models.CharField(blank=True, choices=[('ینبادی', 'ینبادی'), ('پیشرفته', 'پیشرفته')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='available_Job_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_gateway', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
    ]
