# Generated by Django 4.2.3 on 2023-08-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_company_favorite_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city'),
        ),
    ]
