# Generated by Django 4.2.3 on 2023-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_company_active_plan_company_available_job_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_plan',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('10-50', '10-50'), ('50-100', '50-100'), ('100-500', '100-500'), ('بیشتر از 500', 'بیشتر از 500')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
