# Generated by Django 4.2.3 on 2023-08-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_company_join_at_alter_company_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
    ]
