# Generated by Django 4.2.3 on 2023-08-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='registration_file',
        ),
        migrations.AlterField(
            model_name='job',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
