# Generated by Django 4.2.3 on 2023-08-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_job_company'),
        ('base', '0012_remove_verification_registration_file_and_more'),
    ]

    operations = [
    ]
