# Generated by Django 4.2.3 on 2023-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_merge_20230830_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='active_plan',
            field=models.CharField(blank=True, choices=[('ینبادی', 'ینبادی'), ('پیشرفته', 'پیشرفته')], max_length=15, null=True),
        ),
    ]
