# Generated by Django 4.2.3 on 2023-08-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_company_join_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(),
        ),
    ]
