# Generated by Django 4.2.3 on 2023-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_education_from_date_alter_education_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cooperation_type',
            field=models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('خانوم', 'خانوم'), ('آقا', 'آقا')], default='خانوم', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='perfession_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
