# Generated by Django 4.2.3 on 2023-08-09 17:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_apply_company_alter_apply_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='favorite_jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=[], null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
