# Generated by Django 4.2.3 on 2023-08-11 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_employee_favorite_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='favorite_employee',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=[], null=True), size=None),
        ),
    ]
