# Generated by Django 4.2.3 on 2023-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_employee_favorite_jobs_employee_favorite_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='favorite_employee',
        ),
        migrations.AddField(
            model_name='company',
            name='favorite_employee',
            field=models.ManyToManyField(to='base.employee'),
        ),
    ]
