# Generated by Django 4.2.3 on 2023-08-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_company_favorite_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills_required',
            new_name='skills',
        ),
    ]
