# Generated by Django 4.2.3 on 2023-08-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_skills_required_job_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='Company',
        ),
        migrations.AddField(
            model_name='company',
            name='verification',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.verification'),
            preserve_default=False,
        ),
    ]
