# Generated by Django 4.2.3 on 2023-08-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_verification_company_company_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='verification',
        ),
        migrations.AddField(
            model_name='verification',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
    ]
