# Generated by Django 4.2.3 on 2023-08-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_company_verification_verification_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
