# Generated by Django 4.2.3 on 2023-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('فعال', 'فعال'), ('درانتظار تایید', 'درانتظار تایید'), ('حذف شده شده', 'حذف شده شده')], default='در انتظار بررسی', max_length=15),
        ),
    ]
