# Generated by Django 4.2.3 on 2023-08-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_apply_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='Company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='company_name',
        ),
    ]
