export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_DETAILS_UPDATE_REQUEST =
  "CATEGORY_DETAILS_UPDATE_REQUEST";
export const CATEGORY_DETAILS_UPDATE_SUCCESS =
  "CATEGORY_DETAILS_UPDATE_SUCCESS";
export const CATEGORY_DETAILS_UPDATE_FAIL = "CATEGORY_DETAILS_UPDATE_FAIL";

export const CATEGORY_POST_REQUEST = "CATEGORY_POST_REQUEST";
export const CATEGORY_POST_SUCCESS = "CATEGORY_POST_SUCCESS";
export const CATEGORY_POST_FAIL = "CATEGORY_POST_FAIL";

export const PRODUCT_DELETE_REQUEST = " PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
