export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_DETAILS_UPDATE_REQUEST =
  "CATEGORY_DETAILS_UPDATE_REQUEST";
export const CATEGORY_DETAILS_UPDATE_SUCCESS =
  "CATEGORY_DETAILS_UPDATE_SUCCESS";
export const CATEGORY_DETAILS_UPDATE_FAIL = "CATEGORY_DETAILS_UPDATE_FAIL";

export const CATEGORY_POST_REQUEST = "CATEGORY_POST_REQUEST";
export const CATEGORY_POST_SUCCESS = "CATEGORY_POST_SUCCESS";
export const CATEGORY_POST_FAIL = "CATEGORY_POST_FAIL";

export const CATEGORY_DELETE_REQUEST = " CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";

// SKILL
export const SKILL_LIST_REQUEST = "SKILL_LIST_REQUEST";
export const SKILL_LIST_SUCCESS = "SKILL_LIST_SUCCESS";
export const SKILL_LIST_FAIL = "SKILL_LIST_FAIL";

export const SKILL_DETAILS_UPDATE_REQUEST = "SKILL_DETAILS_UPDATE_REQUEST";
export const SKILL_DETAILS_UPDATE_SUCCESS = "SKILL_DETAILS_UPDATE_SUCCESS";
export const SKILL_DETAILS_UPDATE_FAIL = "SKILL_DETAILS_UPDATE_FAIL";

export const SKILL_POST_REQUEST = "SKILL_POST_REQUEST";
export const SKILL_POST_SUCCESS = "SKILL_POST_SUCCESS";
export const SKILL_POST_FAIL = "SKILL_POST_FAIL";

export const SKILL_DELETE_REQUEST = "SKILL_DELETE_REQUEST";
export const SKILL_DELETE_SUCCESS = "SKILL_DELETE_SUCCESS";
export const SKILL_DELETE_FAIL = "SKILL_DELETE_FAIL";

//
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
//
export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_DETAILS_UPDATE_REQUEST = "REVIEW_DETAILS_UPDATE_REQUEST";
export const REVIEW_DETAILS_UPDATE_SUCCESS = "REVIEW_DETAILS_UPDATE_SUCCESS";
export const REVIEW_DETAILS_UPDATE_FAIL = "REVIEW_DETAILS_UPDATE_FAIL";
