export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const COMPANY_JOBS_LIST_REQUEST = "COMPANY_JOBS_LIST_REQUEST";
export const COMPANY_JOBS_LIST_SUCCESS = "COMPANY_JOBS_LIST_SUCCESS";
export const COMPANY_JOBS_LIST_FAIL = "COMPANY_JOBS_LIST_FAIL";

export const COMPANY_REVIEWS_REQUEST = "COMPANY_REVIEWS_REQUEST";
export const COMPANY_REVIEWS_SUCCESS = "COMPANY_REVIEWS_SUCCESS";
export const COMPANY_REVIEWS_FAIL = "COMPANY_REVIEWS_FAIL";

export const COMPANY_FAVORITE_EMPLOYEE_REQUEST =
  "COMPANY_FAVORITE_EMPLOYEE_REQUEST";
export const COMPANY_FAVORITE_EMPLOYEE_SUCCESS =
  "COMPANY_FAVORITE_EMPLOYEE_SUCCESS";
export const COMPANY_FAVORITE_EMPLOYEE_FAIL = "COMPANY_FAVORITE_EMPLOYEE_FAIL";
// POST DATA
export const COMPANY_VERIFICATION_REQUEST = "COMPANY_VERIFICATION_REQUEST";
export const COMPANY_VERIFICATION_SUCCESS = "COMPANY_VERIFICATION_SUCCESS";
export const COMPANY_VERIFICATION_FAIL = "COMPANY_VERIFICATION_FAIL";

export const COMPANY_POST_REVIEW_REQUEST = "COMPANY_POST_REVIEW_REQUEST";
export const COMPANY_POST_REVIEW_SUCCESS = "COMPANY_POST_REVIEW_SUCCESS";
export const COMPANY_POST_REVIEW_FAIL = "COMPANY_POST_REVIEW_FAIL";

export const COMPANY_TOGGLE_FAVORITE_REQUEST = "COMPANY_TOGGLE_FAVORITE_REQUEST";
export const COMPANY_TOGGLE_FAVORITE_SUCCESS = "COMPANY_TOGGLE_FAVORITE_SUCCESS";
export const COMPANY_TOGGLE_FAVORITE_FAIL = "COMPANY_TOGGLE_FAVORITE_FAIL";
// PUT data
export const COMPANY_DETAILS_UPDATE_REQUEST = "COMPANY_DETAILS_UPDATE_REQUEST";
export const COMPANY_DETAILS_UPDATE_SUCCESS = "COMPANY_DETAILS_UPDATE_SUCCESS";
export const COMPANY_DETAILS_UPDATE_FAIL = "COMPANY_DETAILS_UPDATE_FAIL";
//all company
export const COMPANY_LIST_REQUEST = "COMPANY_LIST_REQUEST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAIL = "COMPANY_LIST_FAIL";
//
export const COMPANY_DELETE_REQUEST = "COMPANY_DELETE_REQUEST";
export const COMPANY_DELETE_SUCCESS = "COMPANY_DELETE_SUCCESS";
export const COMPANY_DELETE_FAIL = "COMPANY_DELETE_FAIL";
//
export const COMPANY_POST_REQUEST = "COMPANY_POST_REQUEST";
export const COMPANY_POST_SUCCESS = "COMPANY_POST_SUCCESS";
export const COMPANY_POST_FAIL = "COMPANY_POST_FAIL";
