export const COMPANY_DETAILS_REQUEST = "COMPANY_DETAILS_REQUEST";
export const COMPANY_DETAILS_SUCCESS = "COMPANY_DETAILS_SUCCESS";
export const COMPANY_DETAILS_FAIL = "COMPANY_DETAILS_FAIL";

export const COMPANY_JOBS_LIST_REQUEST = "COMPANY_JOBS_LIST_REQUEST";
export const COMPANY_JOBS_LIST_SUCCESS = "COMPANY_JOBS_LIST_SUCCESS";
export const COMPANY_JOBS_LIST_FAIL = "COMPANY_JOBS_LIST_FAIL";

export const COMPANY_REVIEWS_REQUEST = "COMPANY_REVIEWS_REQUEST";
export const COMPANY_REVIEWS_SUCCESS = "COMPANY_REVIEWS_SUCCESS";
export const COMPANY_REVIEWS_FAIL = "COMPANY_REVIEWS_FAIL";
