export const EMPLOYEE_LIST_ALL_REQUEST = "EMPLOYEE_LIST_ALL_REQUEST";
export const EMPLOYEE_LIST_ALL_SUCCESS = "EMPLOYEE_LIST_ALL_SUCCESS";
export const EMPLOYEE_LIST_ALL_FAIL = "EMPLOYEE_LIST_ALL_FAIL";

export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAIL = "EMPLOYEE_DETAILS_FAIL";

export const EMPLOYEE_PORTFOLIO_DETAILS_REQUEST = "EMPLOYEE_PORTFOLIO_DETAILS_REQUEST";
export const EMPLOYEE_PORTFOLIO_DETAILS_SUCCESS = "EMPLOYEE_PORTFOLIO_DETAILS_SUCCESS";
export const EMPLOYEE_PORTFOLIO_DETAILS_FAIL = "EMPLOYEE_PORTFOLIO_DETAILS_FAIL";

export const EMPLOYEE_FAVORITE_REQUEST = "EMPLOYEE_FAVORITE_REQUEST";
export const EMPLOYEE_FAVORITE_SUCCESS = "EMPLOYEE_FAVORITE_SUCCESS";
export const EMPLOYEE_FAVORITE_FAIL = "EMPLOYEE_FAVORITE_FAIL";

export const EMPLOYEE_TOGGLE_FAVORITE_REQUEST = "EMPLOYEE_TOGGLE_FAVORITE_REQUEST";
export const EMPLOYEE_TOGGLE_FAVORITE_SUCCESS = "EMPLOYEE_TOGGLE_FAVORITE_SUCCESS";
export const EMPLOYEE_TOGGLE_FAVORITE_FAIL = "EMPLOYEE_TOGGLE_FAVORITE_FAIL";

// put
export const EMPLOYEE_DETAILS_EDIT_REQUEST = "EMPLOYEE_DETAILS_EDIT_REQUEST";
export const EMPLOYEE_DETAILS_EDIT_SUCCESS = "EMPLOYEE_DETAILS_EDIT_SUCCESS";
export const EMPLOYEE_DETAILS_EDIT_FAIL = "EMPLOYEE_DETAILS_EDIT_FAIL";

//post
export const EMPLOYEE_PORTFOLIO_POST_REQUEST = "EMPLOYEE_PORTFOLIO_POST_REQUEST";
export const EMPLOYEE_PORTFOLIO_POST_SUCCESS = "EMPLOYEE_PORTFOLIO_POST_SUCCESS";
export const EMPLOYEE_PORTFOLIO_POST_FAIL = "EMPLOYEE_PORTFOLIO_POST_FAIL";
