export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

// export const COMPANY_JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
// export const COMPANY_JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
// export const COMPANY_JOBS_LIST_FAIL = "JOBS_LIST_FAIL";
