export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

export const JOBS_DETAIL_REQUEST = "JOBS_DETAIL_REQUEST";
export const JOBS_DETAIL_SUCCESS = "JOBS_DETAIL_SUCCESS";
export const JOBS_DETAIL_FAIL = "JOBS_DETAIL_FAIL";

export const JOBS_POST_REQUIREMENTS_REQUEST = "JOBS_POST_REQUIREMENTS_REQUEST";
export const JOBS_POST_REQUIREMENTS_SUCCESS = "JOBS_POST_REQUIREMENTS_SUCCESS";
export const JOBS_POST_REQUIREMENTS_FAIL = "JOBS_POST_REQUIREMENTS_FAIL";
//POST
export const JOBS_POST_REQUEST = "JOBS_POST_REQUEST";
export const JOBS_POST_SUCCESS = "JOBS_POST_SUCCESS";
export const JOBS_POST_FAIL = "JOBS_POST_FAIL";
// PUT
export const JOBS_EDIT_DETAILS_REQUEST = "JOBS_EDIT_DETAILS_REQUEST";
export const JOBS_EDIT_DETAILS_SUCCESS = "JOBS_EDIT_DETAILS_SUCCESS";
export const JOBS_EDIT_DETAILS_FAIL = "JOBS_EDIT_DETAILS_FAIL";

export const JOB_DETAILS_UPDATE_REQUEST = "JOB_DETAILS_UPDATE_REQUEST";
export const JOB_DETAILS_UPDATE_SUCCESS = " JOB_DETAILS_UPDATE_SUCCESS";
export const JOB_DETAILS_UPDATE_FAIL = "JOB_DETAILS_UPDATE_FAIL";

export const JOB_DELETE_REQUEST = " JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";
