export const JOBS_LIST_REQUEST = "JOBS_LIST_REQUEST";
export const JOBS_LIST_SUCCESS = "JOBS_LIST_SUCCESS";
export const JOBS_LIST_FAIL = "JOBS_LIST_FAIL";

export const JOBS_DETAIL_REQUEST = "JOBS_DETAIL_REQUEST";
export const JOBS_DETAIL_SUCCESS = "JOBS_DETAIL_SUCCESS";
export const JOBS_DETAIL_FAIL = "JOBS_DETAIL_FAIL";

export const JOBS_POST_REQUIREMENTS_REQUEST = "JOBS_POST_REQUIREMENTS_REQUEST";
export const JOBS_POST_REQUIREMENTS_SUCCESS = "JOBS_POST_REQUIREMENTS_SUCCESS";
export const JOBS_POST_REQUIREMENTS_FAIL = "JOBS_POST_REQUIREMENTS_FAIL";
//POST
export const JOBS_POST_REQUEST = "JOBS_POST_REQUEST";
export const JOBS_POST_SUCCESS = "JOBS_POST_SUCCESS";
export const JOBS_POST_FAIL = "JOBS_POST_FAIL";