export const FREELANCER_REQUESTS_REQUEST = "FREELANCER_REQUESTS_REQUEST";
export const FREELANCER_REQUESTS_SUCCESS = "FREELANCER_REQUESTS_SUCCESS";
export const FREELANCER_REQUESTS_FAIL = "FREELANCER_REQUESTS_FAIL";
