export const FREELANCER_REQUESTS_REQUEST = "FREELANCER_REQUESTS_REQUEST";
export const FREELANCER_REQUESTS_SUCCESS = "FREELANCER_REQUESTS_SUCCESS";
export const FREELANCER_REQUESTS_FAIL = "FREELANCER_REQUESTS_FAIL";

export const FREELANCER_APPLY_POST_REQUEST = "FREELANCER_APPLY_POST_REQUEST";
export const FREELANCER_APPLY_POST_SUCCESS = "FREELANCER_APPLY_POST_SUCCESS";
export const FREELANCER_APPLY_POST_FAIL = "FREELANCER_APPLY_POST_FAIL";
